# Generated by Django 4.2.3 on 2023-08-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='asset_id',
            field=models.IntegerField(),
        ),
    ]
