# Generated by Django 4.2.3 on 2023-07-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='amenities',
            field=models.CharField(choices=[('Balcony', 'Balcony'), ('Sun Room', 'Sun Room'), ('Outdoor Kitchen', 'Outdoor Kitchen'), ('Parking', 'Parking'), ('Air Condition', 'Air Condition'), ('Alarm System', 'Alarm System'), ('Tennis Court', 'Tennis Court'), ('VolleyBall Court', 'VolleyBall Court'), ('Home Theatre', 'Home Theatre'), ('Garden', 'Garden'), ('Children Play Area', 'Children Play Area'), ('Fitness CLub', 'Fitness CLub')], max_length=200),
        ),
    ]
