# Generated by Django 4.2.3 on 2023-08-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_asset_photo_alter_asset_asset_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.IntegerField(),
        ),
    ]
